"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["src/EmBall/EmBall.py"]
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    #Metadata
    name="EmBall",
    author="Andrew Mains",
    author_email="andrewmains12@berkeley.edu",

    #Real data
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['pygame']
)
